# Generated by Django 6.0.6 on 2026-06-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_communityunit_resident_person_type_and_more'),
        ('traffic_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='checkpoint_type',
            field=models.CharField(choices=[('MAIN_GATE', 'Main Gate'), ('COMMUNITY_UNIT', 'Estate/Company')], default='MAIN_GATE', max_length=30),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='community_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.communityunit'),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='gate',
            field=models.CharField(choices=[('CHUNGA_MALI', 'Chunga Mali - Ngecha Road'), ('NAIROBI_NAKURU', 'Nairobi-Nakuru Highway'), ('LIMURU_ROAD', 'Limuru Road')], default='CHUNGA_MALI', max_length=50),
        ),
    ]
