# Generated by Django 6.0.6 on 2026-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_logs', '0002_trafficlog_checkpoint_type_trafficlog_community_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='gate',
            field=models.CharField(blank=True, choices=[('CHUNGA_MALI', 'Chunga Mali - Ngecha Road'), ('NAIROBI_NAKURU', 'Nairobi-Nakuru Highway'), ('LIMURU_ROAD', 'Limuru Road')], default='', max_length=50),
        ),
    ]
