# Generated by Django 6.0.6 on 2026-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(default='Tilisi Estate Traffic Portal', max_length=120)),
                ('logo_url', models.CharField(blank=True, max_length=240)),
                ('contact_phone', models.CharField(default='+254 700 000 000', max_length=40)),
                ('contact_email', models.EmailField(default='security@tilisi.co.ke', max_length=254)),
                ('timezone_name', models.CharField(default='Africa/Nairobi', max_length=80)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('compact_mode', models.BooleanField(default=False)),
                ('sms_simulation_enabled', models.BooleanField(default=True)),
                ('email_simulation_enabled', models.BooleanField(default=False)),
                ('require_visitor_id', models.BooleanField(default=True)),
                ('require_vehicle_details', models.BooleanField(default=False)),
                ('max_visit_hours', models.PositiveIntegerField(default=8)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('failed_login_warning', models.BooleanField(default=True)),
                ('default_report_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System setting',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
