# Generated by Django 6.0.6 on 2026-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RESIDENT', 'Resident'), ('SECURITY', 'Security Guard'), ('MAIN_GATE_GUARD', 'Main Gate Guard'), ('UNIT_GUARD', 'Estate/Company Guard'), ('RECEPTIONIST', 'Company Receptionist')], default='RESIDENT', max_length=20),
        ),
    ]
