# Generated by Django 6.0.6 on 2026-06-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit_type', models.CharField(choices=[('RESIDENTIAL', 'Residential Estate'), ('COMMERCIAL', 'Commercial Company')], max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='person_type',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('EMPLOYEE', 'Employee')], default='RESIDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='community_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='residents.communityunit'),
        ),
    ]
