# Generated by Django 6.0.6 on 2026-06-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('RESIDENT', 'Resident'), ('VISITOR', 'Visitor'), ('SERVICE', 'Service')], default='RESIDENT', max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='residents.resident')),
                ('visitor_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='visitors.visitor')),
            ],
            options={
                'ordering': ('plate_number',),
            },
        ),
    ]
