# Generated by Django 6.0.6 on 2026-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle')], default='CAR', max_length=20),
        ),
    ]
