# Generated by Django 6.0.6 on 2026-06-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_communityunit_resident_person_type_and_more'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='visitor',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='residents.communityunit'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='guest_type',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('DELIVERY', 'Delivery'), ('SERVICE_PROVIDER', 'Service Provider')], default='VISITOR', max_length=30),
        ),
        migrations.AddField(
            model_name='visitor',
            name='main_gate',
            field=models.CharField(blank=True, choices=[('CHUNGA_MALI', 'Chunga Mali - Ngecha Road'), ('NAIROBI_NAKURU', 'Nairobi-Nakuru Highway'), ('LIMURU_ROAD', 'Limuru Road')], max_length=30),
        ),
        migrations.AddField(
            model_name='visitor',
            name='redirected_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_visitors', to='residents.communityunit'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_make_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('ARRIVED_MAIN_GATE', 'Arrived at Main Gate'), ('REDIRECTED', 'Redirected'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out')], default='PENDING', max_length=20),
        ),
    ]
