# Generated by Django 6.0.6 on 2026-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('ARRIVED_MAIN_GATE', 'Arrived at Main Gate'), ('REDIRECTED', 'Redirected'), ('UNIT_CONFIRMED', 'Estate/Company Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKOUT_REQUESTED', 'Checkout Requested'), ('UNIT_EXIT_CONFIRMED', 'Released to Main Gate'), ('CHECKED_OUT', 'Checked Out')], default='PENDING', max_length=20),
        ),
    ]
