# Generated by Django 6.0.6 on 2026-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitor_qr_token_notification_visitorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='expected_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='incident_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='incident_reason',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='visitor',
            name='incident_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
