# Generated by Django 6.0.6 on 2026-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_visitor_recurrence_visitor_recurrence_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vehicle_class',
            field=models.CharField(blank=True, choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle')], max_length=20),
        ),
    ]
